FROM python:3.9.6-slim-buster

WORKDIR /app

ADD . /app

RUN pip install selenium
RUN pip install json
RUN pip install bs4
RUN pip install requests

EXPOSE 9527

CMD ["python", "getPrice/checkData.py"]